# Generated by Django 4.2 on 2025-02-27 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_contactmessage_options_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couples_names', models.CharField(max_length=100, verbose_name="Couple's Names")),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('wedding_date', models.DateField(verbose_name='Wedding Date')),
                ('venue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wedding Venue')),
                ('photography_style', models.CharField(blank=True, choices=[('traditional', 'Traditional'), ('photojournalistic', 'Photojournalistic'), ('artistic', 'Artistic'), ('aerial', 'Aerial'), ('portrait', 'Portrait-focused'), ('black_and_white', 'Black & White')], max_length=20, null=True, verbose_name='Preferred Photography Style')),
                ('budget', models.CharField(blank=True, choices=[('1000-2000', '$1,000 - $2,000'), ('2000-3000', '$2,000 - $3,000'), ('3000-4000', '$3,000 - $4,000'), ('4000-5000', '$4,000 - $5,000'), ('5000+', '$5,000+')], max_length=20, null=True, verbose_name='Approximate Budget')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submission Date')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Has Been Contacted')),
            ],
            options={
                'verbose_name': 'Wedding Booking',
                'verbose_name_plural': 'Wedding Bookings',
                'ordering': ['-wedding_date'],
            },
        ),
    ]
