# Generated by Django 4.2 on 2025-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_savethedate_delete_weddingbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savethedate',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Details'),
        ),
    ]
