# Generated by Django 4.2 on 2025-03-01 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://example.com/default-image.jpg', help_text='URL of the product image.', null=True),
        ),
        migrations.AlterField(
            model_name='savethedate',
            name='message',
            field=models.TextField(blank=True, help_text='Please provide any additional details about your wedding.', null=True, verbose_name='Additional Details'),
        ),
        migrations.AlterField(
            model_name='savethedate',
            name='phone',
            field=models.CharField(blank=True, help_text="Enter your phone number in the format: '+999999999'. Up to 15 digits allowed.", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
